// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"
	models "identity/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// CreatorRepository is an autogenerated mock type for the CreatorRepository type
type CreatorRepository struct {
	mock.Mock
}

// CreateCreator provides a mock function with given fields: ctx, user
func (_m *CreatorRepository) CreateCreator(ctx context.Context, user models.Creator) (models.Creator, error) {
	ret := _m.Called(ctx, user)

	var r0 models.Creator
	if rf, ok := ret.Get(0).(func(context.Context, models.Creator) models.Creator); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(models.Creator)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, models.Creator) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
