pkgname="orm"
no-tests="true"
output="identity/internal/databases/orm"
[psql]
  dbname="awstdev"
  host="localhost"
  port=5432
  user="postgresql"
  pass="postgresql"
  sslmode="disable"
  whitelist=["users","creators"]
  schema="public"