version: '3.8'
services:
  
  api_awstdev_web:
    image: api_awstdev_web
    container_name: api_awstdev_web
    restart: on-failure 
    build:
      dockerfile: build/Dockerfile
      context: .
    ports:
      - 8080:8080
    environment:
      API_PORT: 8080
    networks:
      - new  

  
volumes:
  db:
    driver: local
networks:
    new:    