// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "identity/internal/models"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, user
func (_m *Repository) Create(ctx context.Context, user models.Creator) (models.Creator, error) {
	ret := _m.Called(ctx, user)

	var r0 models.Creator
	if rf, ok := ret.Get(0).(func(context.Context, models.Creator) models.Creator); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(models.Creator)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, models.Creator) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, newCreator
func (_m *Repository) Update(ctx context.Context, newCreator models.Creator) error {
	ret := _m.Called(ctx, newCreator)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Creator) error); ok {
		r0 = rf(ctx, newCreator)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
